<a href="https://colab.research.google.com/github/dmdigrande/dmdigrande.github.io/blob/main/week1-assignment1-pandas-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Assignment - Pandas exercises

## Data

This assignment uses 2019 flight statistics from the United States Department of Transportationâ€™s Bureau of Transportation Statistics (available [here](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FMF&QO_fu146_anzr=Nv4%20Pn44vr45) and in this repository as `data/T100_MARKET_ALL_CARRIER.zip`). Each row contains information about a specific route for a given carrier in a given month (e.g., JFK &rarr; LAX on Delta Airlines in January). There are 321,409 rows and 41 columns. Note that you don't need to unzip the file to read it in with `pd.read_csv()`.

## Exercises

##### 1. Read in the data and convert the column names to lowercase to make them easier to work with.

In [3]:
import pandas as pd

flights = pd.read_csv("./T100_MARKET_ALL_CARRIER.zip")

flights

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

##### 2. What columns are in the data?

In [4]:
flights.columns

Index(['PASSENGERS', 'FREIGHT', 'MAIL', 'DISTANCE', 'UNIQUE_CARRIER',
       'AIRLINE_ID', 'UNIQUE_CARRIER_NAME', 'UNIQUE_CARRIER_ENTITY', 'REGION',
       'CARRIER', 'CARRIER_NAME', 'CARRIER_GROUP', 'CARRIER_GROUP_NEW',
       'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID',
       'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_FIPS',
       'ORIGIN_STATE_NM', 'ORIGIN_COUNTRY', 'ORIGIN_COUNTRY_NAME',
       'ORIGIN_WAC', 'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID',
       'DEST_CITY_MARKET_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR',
       'DEST_STATE_FIPS', 'DEST_STATE_NM', 'DEST_COUNTRY', 'DEST_COUNTRY_NAME',
       'DEST_WAC', 'YEAR', 'QUARTER', 'MONTH', 'DISTANCE_GROUP', 'CLASS',
       'DATA_SOURCE'],
      dtype='object')

##### 3. How many distinct carrier names are in the dataset?

In [5]:
flights.UNIQUE_CARRIER_NAME.value_counts(normalize = True)

Southwest Airlines Co.             0.129390
United Air Lines Inc.              0.062273
Delta Air Lines Inc.               0.057008
SkyWest Airlines Inc.              0.052793
American Airlines Inc.             0.044488
                                     ...
Aviateca, S.A.                     0.000006
Luxaviation Germany GmbH           0.000006
Mjet GmbH                          0.000003
Polaris Aviation Solutions, LLC    0.000003
Sparfell Luftfahrt GmbH            0.000003
Name: UNIQUE_CARRIER_NAME, Length: 318, dtype: float64

##### 4. Calculate the totals of the `freight`, `mail`, and `passengers` columns for flights from the United Kingdom to the United States.

In [6]:
uk_to_us_flights = flights[(flights['ORIGIN_COUNTRY_NAME'] == 'United Kingdom') & (flights['DEST_COUNTRY_NAME'] == 'United States')]
uk_to_us_flights

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
1101,0.0,348930.0,0.0,4011.0,FX,20107,Federal Express Corporation,16196,A,FX,...,Indiana,US,United States,42,2019,1,3,9,G,IU
1102,0.0,33956.0,0.0,4382.0,FX,20107,Federal Express Corporation,16196,A,FX,...,Tennessee,US,United States,54,2019,1,3,9,G,IU
1742,0.0,1785444.0,0.0,3482.0,5X,19917,United Parcel Service,16911,A,5X,...,Pennsylvania,US,United States,23,2019,4,11,7,G,IU
1743,0.0,185326.0,0.0,3976.0,5X,19917,United Parcel Service,16911,A,5X,...,Kentucky,US,United States,52,2019,4,11,8,G,IU
1753,0.0,2004300.0,0.0,4062.0,5X,19917,United Parcel Service,16911,A,5X,...,Kentucky,US,United States,52,2019,4,11,9,G,IU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320984,55479.0,4293824.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,2,5,7,F,IF
321030,56636.0,4161643.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,2,4,7,F,IF
321091,58359.0,4516041.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,4,10,7,F,IF
321114,59123.0,4235134.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,3,8,7,F,IF
321172,61862.0,4715962.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,3,7,7,F,IF

In [162]:
total_freight = uk_to_us_flights['FREIGHT'].sum()
total_mail = uk_to_us_flights['MAIL'].sum()
total_passengers = uk_to_us_flights['PASSENGERS'].sum()

print('TOTAL FREIGHT:' ,  total_freight)
print('TOTAL MAIL:' , total_mail)
print('TOTAL PASSENGERS:' , total_passengers)

TOTAL FREIGHT: 903296879.0
TOTAL MAIL: 29838395.0
TOTAL PASSENGERS: 10685608.0

##### 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).

In [163]:
unique_carrier = flights.drop_duplicates(subset=['CARRIER','ORIGIN', 'DEST'])

In [9]:
unique_carrier['MEDIAN_DISTANCE'] = unique_carrier['DISTANCE'].median()

median_distance_df = unique_carrier.sort_values(by='MEDIAN_DISTANCE', ascending=False)

median_distance_df.head()

<ipython-input-9-37922d47ccae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_carrier['MEDIAN_DISTANCE'] = unique_carrier['DISTANCE'].median()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,MEDIAN_DISTANCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,74,2019,1,3,17,G,IF,763.0
119231,71.0,0.0,0.0,1332.0,OO,20304,SkyWest Airlines Inc.,06700,D,OO,...,US,United States,84,2019,2,6,3,F,DU,763.0
119315,71.0,12161.0,0.0,221.0,UA,19977,United Air Lines Inc.,0A875,D,UA,...,US,United States,52,2019,3,8,1,L,DU,763.0
119317,71.0,11140.0,0.0,651.0,UA,19977,United Air Lines Inc.,0A875,D,UA,...,US,United States,91,2019,3,8,2,L,DU,763.0
119319,71.0,0.0,0.0,9.0,MW,21242,"Mokulele Flight Services, Inc.",01143,D,MW,...,US,United States,2,2019,2,5,1,F,DU,763.0

##### 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.

In [10]:
unique_carrier = unique_carrier.assign(
    TOTAL_CARGO = lambda x: x.MAIL + x.FREIGHT,
    MEAN_DISTANCE = lambda x: x.DISTANCE.mean())

total_cargo_sort = unique_carrier.sort_values(by='TOTAL_CARGO', ascending=False)

total_cargo_sort.head(10)

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,MEDIAN_DISTANCE,TOTAL_CARGO,MEAN_DISTANCE
7129,0.0,61061463.0,5492.0,0.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,3,9,1,G,DU,763.0,61066955.0,1198.448888
3752,0.0,39731643.0,0.0,3122.0,5X,19917,United Parcel Service,06910,D,5X,...,52,2019,3,7,7,G,DU,763.0,39731643.0,1198.448888
592,0.0,21393989.0,0.0,1619.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,1,3,4,G,DU,763.0,21393989.0,1198.448888
5275,0.0,18973929.0,0.0,4680.0,CI,19544,China Airlines Ltd.,9781A,I,CI,...,1,2019,1,2,10,G,IF,763.0,18973929.0,1198.448888
1131,0.0,17646182.0,0.0,3110.0,PO,20100,Polar Air Cargo Airways,06758,D,PO,...,52,2019,1,3,7,P,DU,763.0,17646182.0,1198.448888
4005,0.0,14930601.0,1302114.0,1796.0,5X,19917,United Parcel Service,06910,D,5X,...,52,2019,3,7,4,G,DU,763.0,16232715.0,1198.448888
1810,0.0,15335629.0,0.0,2846.0,5Y,20007,Atlas Air Inc.,06087,D,5Y,...,41,2019,4,11,6,P,DU,763.0,15335629.0,1198.448888
10102,0.0,14378654.0,650757.0,5861.0,5X,19917,United Parcel Service,06910,D,5X,...,482,2019,3,8,12,G,IU,763.0,15029411.0,1198.448888
1791,0.0,14958375.0,0.0,5081.0,5X,19917,United Parcel Service,16913,P,5X,...,1,2019,4,11,11,G,IU,763.0,14958375.0,1198.448888
380,0.0,14076331.0,0.0,946.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,1,3,2,G,DU,763.0,14076331.0,1198.448888

##### 7. Which 10 carriers flew the most passengers out of the United States to another country?

In [165]:
unique_c= flights.drop_duplicates(subset=['CARRIER'])

us_flights = unique_c[(unique_c['ORIGIN_COUNTRY_NAME'] == 'United States') & unique_c['DEST_COUNTRY_NAME'] != 'United States']

us_flights_sorted = us_flights.sort_values(by='PASSENGERS', ascending=False)

us_flights_sorted.head(10)

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
261677,5272.0,2108.0,0.0,3819.0,NQ,20209,Air Japan Co,9736J,I,NQ,...,NaN,JP,Japan,736,2019,2,4,8,F,IF
261628,5267.0,207427.0,0.0,6352.0,KU,19616,Kuwait Airways Corp.,9644A,I,KU,...,NaN,KW,Kuwait,644,2019,1,2,13,F,IF
259793,5123.0,570792.0,0.0,4406.0,4M,21084,LAN Argentina,71009,I,4M,...,NaN,AR,Argentina,303,2019,3,7,9,F,IF
253289,4654.0,0.0,0.0,4117.0,D7,21657,Air Asia X Berhad dba Airasia X,71151,I,D7,...,NaN,JP,Japan,736,2019,2,4,9,F,IF
245758,4199.0,251502.0,0.0,4694.0,PS,21608,Ukraine International Airlines,71138,I,PS,...,NaN,UA,Ukraine,488,2019,4,11,10,F,IF
241313,3974.0,0.0,0.0,1792.0,LJ,21416,Jin Air Co Ltd.,71086,I,LJ,...,U.S. Pacific Trust Territories and Possessions,US,United States,5,2019,4,10,4,F,IF
233563,3604.0,0.0,0.0,1486.0,9V,21142,"Avior Airlines, C.A.",71024,I,9V,...,Florida,US,United States,33,2019,1,2,3,F,IF
227429,3317.0,10976.0,0.0,5302.0,PR,19564,Philippine Airlines Inc.,9766A,I,PR,...,NaN,PH,Philippines,766,2019,3,9,11,F,IF
219392,2907.0,5738.0,0.0,2194.0,GU,22005,"Aviateca, S.A.",71207,I,GU,...,NaN,GT,Guatemala,127,2019,1,1,5,F,IF
216405,2757.0,218867.0,0.0,7360.0,KQ,21949,Kenya Airways PLC,71197,I,KQ,...,NaN,KE,Kenya,535,2019,1,2,15,F,IF

8. For each of the carriers found in *#7*, find the most popular destination country outside of the United States.

In [185]:
#source: https://stackoverflow.com/questions/39922986/how-do-i-pandas-group-by-to-get-sum

carriers = ['NQ',"KU","4M","D7","PS","LJ","9V","PR","GU","KQ"]

popular_destination = us_flights[us_flights['DEST_COUNTRY_NAME'] != 'United States']

popular_destination = popular_destination[popular_destination['UNIQUE_CARRIER'].isin(carriers)]

#popular_destination = popular_destination.groupby(['DEST_CITY_NAME','PASSENGERS']).sum()

popular_destination = popular_destination.sort_values(by='PASSENGERS', ascending=False)
popular_destination = popular_destination.groupby('DEST_CITY_NAME').sum()

popular_destination

<ipython-input-185-9737569d324d>:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  popular_destination = popular_destination.groupby('DEST_CITY_NAME').sum()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,AIRLINE_ID,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP
DEST_CITY_NAME,,,,,,,,,,,,,,,,,,,,,
"Ezeiza, Argentina",5123.0,570792.0,0.0,4406.0,21084,0,0,13303,1330303,32467,...,33,11625,1162505,30181,0.0,303,2019,3,7,9
"Guatemala City, Guatemala",2907.0,5738.0,0.0,2194.0,22005,0,0,12892,1289208,32575,...,91,12010,1201005,32010,0.0,127,2019,1,1,5
"Kiev, Ukraine",4199.0,251502.0,0.0,4694.0,21608,0,0,12478,1247805,31703,...,22,12627,1262703,32287,0.0,488,2019,4,11,10
"Kuwait, Kuwait",5267.0,207427.0,0.0,6352.0,19616,0,0,12478,1247805,31703,...,22,12849,1284904,32849,0.0,644,2019,1,2,13
"Manila, Philippines",3317.0,10976.0,0.0,5302.0,19564,0,0,12173,1217305,32134,...,2,13408,1340802,33408,0.0,766,2019,3,9,11
"Nairobi, Kenya",2757.0,218867.0,0.0,7360.0,21949,0,0,12478,1247805,31703,...,22,13616,1361602,33616,0.0,535,2019,1,2,15
"Osaka, Japan",4654.0,0.0,0.0,4117.0,21657,0,0,12173,1217305,32134,...,2,12699,1269902,32400,0.0,736,2019,2,4,9
"Tokyo, Japan",5272.0,2108.0,0.0,3819.0,20209,0,0,12173,1217305,32134,...,2,13744,1374406,32169,0.0,736,2019,2,4,8

##### 9. For each of the carriers found in *#7*, find the total number of passengers flown on international flights to/from the destinations in *#8* or the United States. Note that this dataset only has data for flights with an origin and/or destination of the United States.

In [ ]:
us_flights_sorted.head(10)

In [200]:
#how to get the sum of passengers for each destination name without it being for each individual flight??

carriers = ['NQ',"KU","4M","D7","PS","LJ","9V","PR","GU","KQ"]
countries = ['Japan', 'Kenya', 'Philippines','Kuwait','Ukraine', 'Guatemala', 'Argentina']

filtered_flights = flights[flights['DEST_COUNTRY_NAME'].isin(countries) & flights['UNIQUE_CARRIER'].isin(carriers)]

passengers_by_destination = filtered_flights.groupby(['DEST_COUNTRY_NAME', 'UNIQUE_CARRIER', 'PASSENGERS']).sum()

#passengers_by_destination = filtered_flights.sort_values(by = 'PASSENGERS', ascending= False)

passengers_by_destination
#passengers_by_destination = filtered_flights.sort_values['PASSENGERS'].sum()

<ipython-input-200-b54a2f850eb2>:6: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  passengers_by_destination = filtered_flights.groupby(['DEST_COUNTRY_NAME', 'UNIQUE_CARRIER', 'PASSENGERS']).sum()

                                              FREIGHT  MAIL  DISTANCE  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0      570792.0   0.0    4406.0
                                 5648.0      506697.0   0.0    4406.0
                                 5727.0      494674.0   0.0    4406.0
                                 6050.0      460539.0   0.0    4406.0
                                 6056.0      564076.0   0.0    4406.0
...                                               ...   ...       ...
Ukraine           PS             8474.0      351749.0   0.0    4694.0
                                 9063.0      327191.0   0.0    4694.0
                                 9148.0      241815.0   0.0    4694.0
                                 10383.0     278428.0   0.0    4694.0
                                 10417.0     279983.0   0.0    4694.0

                                             AIRLINE_ID  CARRIER_GROUP  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0           21084              0
                                 5648.0           21084              0
                                 5727.0           21084              0
                                 6050.0           21084              0
                                 6056.0           21084              0
...                                                 ...            ...
Ukraine           PS             8474.0           21608              0
                                 9063.0           21608              0
                                 9148.0           21608              0
                                 10383.0          21608              0
                                 10417.0          21608              0

                                             CARRIER_GROUP_NEW  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                      0
                                 5648.0                      0
                                 5727.0                      0
                                 6050.0                      0
                                 6056.0                      0
...                                                        ...
Ukraine           PS             8474.0                      0
                                 9063.0                      0
                                 9148.0                      0
                                 10383.0                     0
                                 10417.0                     0

                                             ORIGIN_AIRPORT_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                  13303
                                 5648.0                  13303
                                 5727.0                  13303
                                 6050.0                  13303
                                 6056.0                  13303
...                                                        ...
Ukraine           PS             8474.0                  12478
                                 9063.0                  12478
                                 9148.0                  12478
                                 10383.0                 12478
                                 10417.0                 12478

                                             ORIGIN_AIRPORT_SEQ_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                    1330303
                                 5648.0                    1330303
                                 5727.0                    1330303
                                 6050.0                    1330303
                                 6056.0                    1330303
...                                                            ...
Ukraine           PS             8474.0                    1247805
                                 9063.0                    1247805
                                 9148.0                    1247805
                                 10383.0                   1247805
                                 10417.0                   1247805

                                             ORIGIN_CITY_MARKET_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                      32467
                                 5648.0                      32467
                                 5727.0                      32467
                                 6050.0                      32467
                                 6056.0                      32467
...                                                            ...
Ukraine           PS             8474.0                      31703
                                 9063.0                      31703
                                 9148.0                      31703
                                 10383.0                     31703
                                 10417.0                     31703

                                             ORIGIN_STATE_FIPS  ORIGIN_WAC  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                   12.0          33
                                 5648.0                   12.0          33
                                 5727.0                   12.0          33
                                 6050.0                   12.0          33
                                 6056.0                   12.0          33
...                                                        ...         ...
Ukraine           PS             8474.0                   36.0          22
                                 9063.0                   36.0          22
                                 9148.0                   36.0          22
                                 10383.0                  36.0          22
                                 10417.0                  36.0          22

                                             DEST_AIRPORT_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                11625
                                 5648.0                11625
                                 5727.0                11625
                                 6050.0                11625
                                 6056.0                11625
...                                                      ...
Ukraine           PS             8474.0                12627
                                 9063.0                12627
                                 9148.0                12627
                                 10383.0               12627
                                 10417.0               12627

                                             DEST_AIRPORT_SEQ_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                  1162505
                                 5648.0                  1162505
                                 5727.0                  1162505
                                 6050.0                  1162505
                                 6056.0                  1162505
...                                                          ...
Ukraine           PS             8474.0                  1262703
                                 9063.0                  1262703
                                 9148.0                  1262703
                                 10383.0                 1262703
                                 10417.0                 1262703

                                             DEST_CITY_MARKET_ID  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                    30181
                                 5648.0                    30181
                                 5727.0                    30181
                                 6050.0                    30181
                                 6056.0                    30181
...                                                          ...
Ukraine           PS             8474.0                    32287
                                 9063.0                    32287
                                 9148.0                    32287
                                 10383.0                   32287
                                 10417.0                   32287

                                             DEST_STATE_FIPS  DEST_WAC  YEAR  \
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0                  0.0       303  2019
                                 5648.0                  0.0       303  2019
                                 5727.0                  0.0       303  2019
                                 6050.0                  0.0       303  2019
                                 6056.0                  0.0       303  2019
...                                                      ...       ...   ...
Ukraine           PS             8474.0                  0.0       488  2019
                                 9063.0                  0.0       488  2019
                                 9148.0                  0.0       488  2019
                                 10383.0                 0.0       488  2019
                                 10417.0                 0.0       488  2019

                                             QUARTER  MONTH  DISTANCE_GROUP
DEST_COUNTRY_NAME UNIQUE_CARRIER PASSENGERS
Argentina         4M             5123.0            3      7               9
                                 5648.0            3      9               9
                                 5727.0            2      4               9
                                 6050.0            2      6               9
                                 6056.0            4     11               9
...                                              ...    ...             ...
Ukraine           PS             8474.0            3      9              10
                                 9063.0            3      8              10
                                 9148.0            3      7              10
                                 10383.0           2      6              10
                                 10417.0           2      5              10

[109 rows x 20 columns]

##### 10. Between which two cities were the most passengers flown? Make sure to account for both directions.

In [38]:
popular_destination1 = flights.groupby(['DEST_CITY_NAME','PASSENGERS']).sum()

popular_destination1 = popular_destination1.sort_values(by='PASSENGERS', ascending=False)
popular_destination1.head(1)

<ipython-input-38-9cc945aa787f>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  popular_destination1 = flights.groupby(['DEST_CITY_NAME','PASSENGERS']).sum()

,,FREIGHT,MAIL,DISTANCE,AIRLINE_ID,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_STATE_FIPS,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP
DEST_CITY_NAME,PASSENGERS,,,,,,,,,,,,,,,,,,,,
"Anchorage, AK",97644.0,390399.0,44506.0,1448.0,19930,3,3,14747,1474703,30559,53.0,93,10299,1029906,30299,2.0,1,2019,3,7,3

In [39]:
popular_origin = flights.groupby(['ORIGIN_CITY_NAME', 'PASSENGERS']).sum()
popular_origin = popular_origin.sort_values(by= 'PASSENGERS', ascending=False)
popular_origin.head(1)

<ipython-input-39-8d10d0d78589>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  popular_origin = flights.groupby(['ORIGIN_CITY_NAME', 'PASSENGERS']).sum()

,,FREIGHT,MAIL,DISTANCE,AIRLINE_ID,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_STATE_FIPS,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP
ORIGIN_CITY_NAME,PASSENGERS,,,,,,,,,,,,,,,,,,,,
"Seattle, WA",97644.0,390399.0,44506.0,1448.0,19930,3,3,14747,1474703,30559,53.0,93,10299,1029906,30299,2.0,1,2019,3,7,3

##### 11. Find the top 3 carriers for the pair of cities found in *#10* and calculate the percentage of passengers each accounted for.

In [151]:
#is this right???


top_passengers = flights[(flights['ORIGIN_CITY_NAME'] == 'Seattle, WA') & (flights['DEST_CITY_NAME'] == 'Anchorage, AK')]

top_passengers_sorted = top_passengers.sort_values(by='PASSENGERS', ascending=False)

total_passengers = top_passengers_sorted['PASSENGERS'].sum()

top_passengers_sorted = top_passengers_sorted.assign(
    PASSENGER_PERCENTAGE= lambda x: x['PASSENGERS'] / total_passengers * 100
)
top_passengers_sorted.head(30)

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,PASSENGER_PERCENTAGE
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,3,7,3,F,DU,9.487802
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,2,6,3,F,DU,9.426295
321393,91330.0,368246.0,63545.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,3,8,3,F,DU,8.874288
321364,80386.0,526417.0,61011.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,2,5,3,F,DU,7.810889
321214,65164.0,380776.0,53148.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,3,9,3,F,DU,6.331809
321186,62668.0,518822.0,60509.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,4,12,3,F,DU,6.089279
321182,62459.0,435745.0,63640.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,1,3,3,F,DU,6.068971
321118,59276.0,512956.0,41853.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,4,10,3,F,DU,5.759688
321023,56417.0,519592.0,77469.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,2,4,3,F,DU,5.481887
320966,54924.0,473313.0,56181.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,4,11,3,F,DU,5.336816
320957,54787.0,408472.0,93422.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,1,1,3,F,DU,5.323504
320538,47595.0,397888.0,55881.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,1,2,3,F,DU,4.624677
317201,29340.0,50777.0,31643.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,3,7,3,F,DU,2.850888
316361,27034.0,53686.0,24998.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,3,8,3,F,DU,2.626820
315180,24483.0,44326.0,32465.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,2,6,3,F,DU,2.378947
307786,16091.0,57031.0,18977.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,2,5,3,F,DU,1.563519
306765,15317.0,55199.0,29338.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,3,9,3,F,DU,1.488311
301758,12610.0,58150.0,22665.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,1,3,3,F,DU,1.225279
301040,12284.0,97028.0,44110.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,4,12,3,F,DU,1.193603
297839,11020.0,46404.0,12851.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,2,4,3,F,DU,1.070783
296298,10499.0,52527.0,46559.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,4,10,3,F,DU,1.020159
293669,9736.0,66363.0,32264.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,4,11,3,F,DU,0.946021
293062,9581.0,59131.0,5533.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,1,1,3,F,DU,0.930960
290708,9033.0,57213.0,2260.0,1448.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,1,2019,1,2,3,F,DU,0.877712
241494,3983.0,0.0,0.0,1448.0,B6,20409,JetBlue Airways,06673,D,B6,...,US,United States,1,2019,2,6,3,F,DU,0.387017
228322,3360.0,0.0,0.0,1448.0,B6,20409,JetBlue Airways,06673,D,B6,...,US,United States,1,2019,3,7,3,F,DU,0.326482
214889,2684.0,0.0,0.0,1448.0,B6,20409,JetBlue Airways,06673,D,B6,...,US,United States,1,2019,3,8,3,F,DU,0.260797
182544,1396.0,0.0,0.0,1448.0,B6,20409,JetBlue Airways,06673,D,B6,...,US,United States,1,2019,2,5,3,F,DU,0.135646
166571,902.0,0.0,0.0,1448.0,B6,20409,JetBlue Airways,06673,D,B6,...,US,United States,1,2019,3,9,3,F,DU,0.087645
132411,139.0,0.0,0.0,1448.0,GL,20402,Miami Air International,06690,D,GL,...,US,United States,1,2019,3,9,3,L,DU,0.013506

##### 12. Find the percentage of international travel per country using total passengers on class F flights.

In [114]:
class_f_flights = us_flights[us_flights['CLASS']== 'F']

class_f_flights['PASSENGER_PERCENTAGE'] = class_f_flights['PASSENGERS'] / total_pass

<ipython-input-114-7e38c64457c8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  class_f_flights['PASSENGER_PERCENTAGE'] = class_f_flights['PASSENGERS'] / total_pass

In [154]:
passengers_per_country = class_f_flights.groupby(['DEST_COUNTRY_NAME','PASSENGERS']).sum()

total_pass = class_f_flights['PASSENGERS'].sum()

passengers_per_country.head(4)

<ipython-input-154-799c0a30827e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  passengers_per_country = class_f_flights.groupby(['DEST_COUNTRY_NAME','PASSENGERS']).sum()

                               FREIGHT  MAIL  DISTANCE  AIRLINE_ID  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0           0.0   0.0    4598.0       19535
                  5123.0      570792.0   0.0    4406.0       21084
Belgium           191.0        26741.0   0.0    3892.0       21567
Brazil            35.0             0.0   0.0    3777.0       21605

                              CARRIER_GROUP  CARRIER_GROUP_NEW  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0                  0                  0
                  5123.0                  0                  0
Belgium           191.0                   0                  0
Brazil            35.0                    0                  0

                              ORIGIN_AIRPORT_ID  ORIGIN_AIRPORT_SEQ_ID  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0                  13204                1320402
                  5123.0                  13303                1330303
Belgium           191.0                   12264                1226402
Brazil            35.0                    13204                1320402

                              ORIGIN_CITY_MARKET_ID  ORIGIN_STATE_FIPS  ...  \
DEST_COUNTRY_NAME PASSENGERS                                            ...
Argentina         1369.0                      31454               12.0  ...
                  5123.0                      32467               12.0  ...
Belgium           191.0                       30852               51.0  ...
Brazil            35.0                        31454               12.0  ...

                              DEST_AIRPORT_ID  DEST_AIRPORT_SEQ_ID  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0                11625              1162505
                  5123.0                11625              1162505
Belgium           191.0                 10752              1075205
Brazil            35.0                  10758              1075806

                              DEST_CITY_MARKET_ID  DEST_STATE_FIPS  DEST_WAC  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0                    30181              0.0       303
                  5123.0                    30181              0.0       303
Belgium           191.0                     30752              0.0       409
Brazil            35.0                      30758              0.0       316

                              YEAR  QUARTER  MONTH  DISTANCE_GROUP  \
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0      2019        4     12              10
                  5123.0      2019        3      7               9
Belgium           191.0       2019        1      3               8
Brazil            35.0        2019        3      9               8

                              PASSENGER_PERCENTAGE
DEST_COUNTRY_NAME PASSENGERS
Argentina         1369.0                  0.025030
                  5123.0                  0.093667
Belgium           191.0                   0.003492
Brazil            35.0                    0.000640

[4 rows x 21 columns]

##### 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in *#12* that used the carriers found in *#11*.

In [156]:
#help

crosstab_table = pd.crosstab(
    (class_f_flights['UNIQUE_CARRIER_NAME'] == ['Alaska Airlines Inc.', 'Delta Air Lines Inc.','JetBlue Airways']),
    class_f_flights['DEST_COUNTRY_NAME'] == ['Argentina', 'Belgium', 'Brazil'],
    values=class_f_flights['PASSENGERS'],
    aggfunc='sum',
    normalize='index')

crosstab_table

ValueError: ignored

In [134]:
filtered_flights = class_f_flights[(class_f_flights['UNIQUE_CARRIER_NAME'] == 'Alaska Airlines Inc.') &
 (class_f_flights['DEST_COUNTRY_NAME'].isin(['Argentina', 'Belgium', 'United States']) &
  (class_f_flights['ORIGIN_COUNTRY_NAME'].isin(['Argentina', 'Belgium', 'United States'])))]

crosstab_table = pd.crosstab(filtered_flights['UNIQUE_CARRIER_NAME'], filtered_flights['DEST_COUNTRY_NAME'],
                             values=filtered_flights['PASSENGERS'], aggfunc='sum', normalize='index')

crosstab_table

Empty DataFrame
Columns: []
Index: []

##### 14. Create a pivot table showing the total passengers transported between cities in the United States and other countries by the carriers identified in *#7*. Select the top 10 US cities and top 10 international countries from the result.

In [13]:
#help

##### 15: For the top 15 international countries, find the percentage of class F passengers traveling to/from the top 10 US cities for international travel (e.g. if only cities A, B, and C flew into Aruba, the sum of the Aruba row/column would be 1). Plot the result as a heatmap.

In [13]:
#help