<a href="https://colab.research.google.com/github/dmdigrande/dmdigrande.github.io/blob/main/week1-assignment1-pandas-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Assignment - Pandas exercises

## Data

This assignment uses 2019 flight statistics from the United States Department of Transportationâ€™s Bureau of Transportation Statistics (available [here](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FMF&QO_fu146_anzr=Nv4%20Pn44vr45) and in this repository as `data/T100_MARKET_ALL_CARRIER.zip`). Each row contains information about a specific route for a given carrier in a given month (e.g., JFK &rarr; LAX on Delta Airlines in January). There are 321,409 rows and 41 columns. Note that you don't need to unzip the file to read it in with `pd.read_csv()`.

## Exercises

##### 1. Read in the data and convert the column names to lowercase to make them easier to work with.

In [5]:
import pandas as pd

flights = pd.read_csv("./T100_MARKET_ALL_CARRIER.zip")

flights

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

##### 2. What columns are in the data?

In [6]:
flights.columns

Index(['PASSENGERS', 'FREIGHT', 'MAIL', 'DISTANCE', 'UNIQUE_CARRIER',
       'AIRLINE_ID', 'UNIQUE_CARRIER_NAME', 'UNIQUE_CARRIER_ENTITY', 'REGION',
       'CARRIER', 'CARRIER_NAME', 'CARRIER_GROUP', 'CARRIER_GROUP_NEW',
       'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID',
       'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_FIPS',
       'ORIGIN_STATE_NM', 'ORIGIN_COUNTRY', 'ORIGIN_COUNTRY_NAME',
       'ORIGIN_WAC', 'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID',
       'DEST_CITY_MARKET_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR',
       'DEST_STATE_FIPS', 'DEST_STATE_NM', 'DEST_COUNTRY', 'DEST_COUNTRY_NAME',
       'DEST_WAC', 'YEAR', 'QUARTER', 'MONTH', 'DISTANCE_GROUP', 'CLASS',
       'DATA_SOURCE'],
      dtype='object')

##### 3. How many distinct carrier names are in the dataset?

In [7]:
flights.UNIQUE_CARRIER_NAME.value_counts(normalize = True)

Southwest Airlines Co.             0.129390
United Air Lines Inc.              0.062273
Delta Air Lines Inc.               0.057008
SkyWest Airlines Inc.              0.052793
American Airlines Inc.             0.044488
                                     ...
Aviateca, S.A.                     0.000006
Luxaviation Germany GmbH           0.000006
Mjet GmbH                          0.000003
Polaris Aviation Solutions, LLC    0.000003
Sparfell Luftfahrt GmbH            0.000003
Name: UNIQUE_CARRIER_NAME, Length: 318, dtype: float64

##### 4. Calculate the totals of the `freight`, `mail`, and `passengers` columns for flights from the United Kingdom to the United States.

In [8]:
uk_to_us_flights = flights[(flights['ORIGIN_COUNTRY_NAME'] == 'United Kingdom') & (flights['DEST_COUNTRY_NAME'] == 'United States')]
uk_to_us_flights

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
1101,0.0,348930.0,0.0,4011.0,FX,20107,Federal Express Corporation,16196,A,FX,...,Indiana,US,United States,42,2019,1,3,9,G,IU
1102,0.0,33956.0,0.0,4382.0,FX,20107,Federal Express Corporation,16196,A,FX,...,Tennessee,US,United States,54,2019,1,3,9,G,IU
1742,0.0,1785444.0,0.0,3482.0,5X,19917,United Parcel Service,16911,A,5X,...,Pennsylvania,US,United States,23,2019,4,11,7,G,IU
1743,0.0,185326.0,0.0,3976.0,5X,19917,United Parcel Service,16911,A,5X,...,Kentucky,US,United States,52,2019,4,11,8,G,IU
1753,0.0,2004300.0,0.0,4062.0,5X,19917,United Parcel Service,16911,A,5X,...,Kentucky,US,United States,52,2019,4,11,9,G,IU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320984,55479.0,4293824.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,2,5,7,F,IF
321030,56636.0,4161643.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,2,4,7,F,IF
321091,58359.0,4516041.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,4,10,7,F,IF
321114,59123.0,4235134.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,3,8,7,F,IF
321172,61862.0,4715962.0,0.0,3452.0,BA,19540,British Airways Plc,9493E,I,BA,...,New York,US,United States,22,2019,3,7,7,F,IF

In [9]:
total_freight = uk_to_us_flights['FREIGHT'].sum()
total_mail = uk_to_us_flights['MAIL'].sum()
total_passengers = uk_to_us_flights['PASSENGERS'].sum()

print(total_freight)
print(total_mail)
print(total_passengers)

903296879.0
29838395.0
10685608.0

##### 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).

In [54]:
unique_carrier = flights.drop_duplicates(subset=['CARRIER','ORIGIN', 'DEST'])

unique_carrier.head()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF

In [19]:
unique_carrier['MEDIAN_DISTANCE'] = unique_carrier['DISTANCE'].median()

median_distance_df = unique_carrier.sort_values(by='MEDIAN_DISTANCE', ascending=False)

median_distance_df.head()

<ipython-input-19-37922d47ccae>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_carrier['MEDIAN_DISTANCE'] = unique_carrier['DISTANCE'].median()

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,MEDIAN_DISTANCE
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,74,2019,1,3,17,G,IF,763.0
119231,71.0,0.0,0.0,1332.0,OO,20304,SkyWest Airlines Inc.,06700,D,OO,...,US,United States,84,2019,2,6,3,F,DU,763.0
119315,71.0,12161.0,0.0,221.0,UA,19977,United Air Lines Inc.,0A875,D,UA,...,US,United States,52,2019,3,8,1,L,DU,763.0
119317,71.0,11140.0,0.0,651.0,UA,19977,United Air Lines Inc.,0A875,D,UA,...,US,United States,91,2019,3,8,2,L,DU,763.0
119319,71.0,0.0,0.0,9.0,MW,21242,"Mokulele Flight Services, Inc.",01143,D,MW,...,US,United States,2,2019,2,5,1,F,DU,763.0

##### 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.

In [27]:
unique_carrier = unique_carrier.assign(
    TOTAL_CARGO = lambda x: x.MAIL + x.FREIGHT,
    MEAN_DISTANCE = lambda x: x.DISTANCE.mean())

total_cargo_sort = unique_carrier.sort_values(by='TOTAL_CARGO', ascending=False)

total_cargo_sort.head(10)

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,MEDIAN_DISTANCE,TOTAL_CARGO,MEAN_DISTANCE
7129,0.0,61061463.0,5492.0,0.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,3,9,1,G,DU,763.0,61066955.0,1198.448888
3752,0.0,39731643.0,0.0,3122.0,5X,19917,United Parcel Service,06910,D,5X,...,52,2019,3,7,7,G,DU,763.0,39731643.0,1198.448888
592,0.0,21393989.0,0.0,1619.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,1,3,4,G,DU,763.0,21393989.0,1198.448888
5275,0.0,18973929.0,0.0,4680.0,CI,19544,China Airlines Ltd.,9781A,I,CI,...,1,2019,1,2,10,G,IF,763.0,18973929.0,1198.448888
1131,0.0,17646182.0,0.0,3110.0,PO,20100,Polar Air Cargo Airways,06758,D,PO,...,52,2019,1,3,7,P,DU,763.0,17646182.0,1198.448888
4005,0.0,14930601.0,1302114.0,1796.0,5X,19917,United Parcel Service,06910,D,5X,...,52,2019,3,7,4,G,DU,763.0,16232715.0,1198.448888
1810,0.0,15335629.0,0.0,2846.0,5Y,20007,Atlas Air Inc.,06087,D,5Y,...,41,2019,4,11,6,P,DU,763.0,15335629.0,1198.448888
10102,0.0,14378654.0,650757.0,5861.0,5X,19917,United Parcel Service,06910,D,5X,...,482,2019,3,8,12,G,IU,763.0,15029411.0,1198.448888
1791,0.0,14958375.0,0.0,5081.0,5X,19917,United Parcel Service,16913,P,5X,...,1,2019,4,11,11,G,IU,763.0,14958375.0,1198.448888
380,0.0,14076331.0,0.0,946.0,FX,20107,Federal Express Corporation,06200,D,FX,...,54,2019,1,3,2,G,DU,763.0,14076331.0,1198.448888

##### 7. Which 10 carriers flew the most passengers out of the United States to another country?

In [36]:
unique_c= flights.drop_duplicates(subset=['CARRIER'])

us_flights = unique_c[(unique_c['ORIGIN_COUNTRY_NAME'] == 'United States')]

us_flights_sorted = us_flights.sort_values(by='PASSENGERS', ascending=False)

us_flights_sorted.head(10)

,PASSENGERS,FREIGHT,MAIL,DISTANCE,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,...,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE
261677,5272.0,2108.0,0.0,3819.0,NQ,20209,Air Japan Co,9736J,I,NQ,...,NaN,JP,Japan,736,2019,2,4,8,F,IF
261628,5267.0,207427.0,0.0,6352.0,KU,19616,Kuwait Airways Corp.,9644A,I,KU,...,NaN,KW,Kuwait,644,2019,1,2,13,F,IF
259793,5123.0,570792.0,0.0,4406.0,4M,21084,LAN Argentina,71009,I,4M,...,NaN,AR,Argentina,303,2019,3,7,9,F,IF
253289,4654.0,0.0,0.0,4117.0,D7,21657,Air Asia X Berhad dba Airasia X,71151,I,D7,...,NaN,JP,Japan,736,2019,2,4,9,F,IF
245758,4199.0,251502.0,0.0,4694.0,PS,21608,Ukraine International Airlines,71138,I,PS,...,NaN,UA,Ukraine,488,2019,4,11,10,F,IF
227429,3317.0,10976.0,0.0,5302.0,PR,19564,Philippine Airlines Inc.,9766A,I,PR,...,NaN,PH,Philippines,766,2019,3,9,11,F,IF
219392,2907.0,5738.0,0.0,2194.0,GU,22005,"Aviateca, S.A.",71207,I,GU,...,NaN,GT,Guatemala,127,2019,1,1,5,F,IF
216405,2757.0,218867.0,0.0,7360.0,KQ,21949,Kenya Airways PLC,71197,I,KQ,...,NaN,KE,Kenya,535,2019,1,2,15,F,IF
203704,2165.0,0.0,0.0,1506.0,4C,21463,Aerovias de Intergracian Regional,71100,I,4C,...,NaN,CO,Colombia,327,2019,3,9,4,F,IF
186805,1539.0,96345.0,0.0,5843.0,MS,19747,Egyptair,9591A,I,MS,...,NaN,EG,Egypt,591,2019,3,9,12,F,IF

8. For each of the carriers found in *#7*, find the most popular destination country outside of the United States.

In [64]:
#source: https://stackoverflow.com/questions/39922986/how-do-i-pandas-group-by-to-get-sum

popular_destination = us_flights[us_flights['DEST_COUNTRY_NAME'] != 'United States']

popular_destination = popular_destination.groupby(['DEST_CITY_NAME','PASSENGERS']).sum()

popular_destination = popular_destination.sort_values(by='PASSENGERS', ascending=False)
popular_destination.head(1)

<ipython-input-64-fa223b74af63>:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  popular_destination = popular_destination.groupby(['DEST_CITY_NAME','PASSENGERS']).sum()

,,FREIGHT,MAIL,DISTANCE,AIRLINE_ID,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN_STATE_FIPS,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST_STATE_FIPS,DEST_WAC,YEAR,QUARTER,MONTH,DISTANCE_GROUP
DEST_CITY_NAME,PASSENGERS,,,,,,,,,,,,,,,,,,,,
"Tokyo, Japan",5272.0,2108.0,0.0,3819.0,20209,0,0,12173,1217305,32134,15.0,2,13744,1374406,32169,0.0,736,2019,2,4,8

##### 9. For each of the carriers found in *#7*, find the total number of passengers flown on international flights to/from the destinations in *#8* or the United States. Note that this dataset only has data for flights with an origin and/or destination of the United States.

##### 10. Between which two cities were the most passengers flown? Make sure to account for both directions.

##### 11. Find the top 3 carriers for the pair of cities found in *#10* and calculate the percentage of passengers each accounted for.

##### 12. Find the percentage of international travel per country using total passengers on class F flights.

##### 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in *#12* that used the carriers found in *#11*.

##### 14. Create a pivot table showing the total passengers transported between cities in the United States and other countries by the carriers identified in *#7*. Select the top 10 US cities and top 10 international countries from the result.

##### 15: For the top 15 international countries, find the percentage of class F passengers traveling to/from the top 10 US cities for international travel (e.g. if only cities A, B, and C flew into Aruba, the sum of the Aruba row/column would be 1). Plot the result as a heatmap.